CREATE DATABASE multitablados;
DROP DATABASE multitablados;
USE multitablados;

CREATE TABLE PROVEEDOR (
    ID_PROV INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(20) NOT NULL,
    CUID VARCHAR(20) NOT NULL,
    CIUDAD VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID_PROV)
);

CREATE TABLE CLIENTE (
    ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE VENDEDOR (
    ID_EMPLEADO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDO VARCHAR(20) NOT NULL,
    DNI INT NOT NULL,
    CIUDAD VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID_EMPLEADO)
);

CREATE TABLE VENTA (
    NRO_FACTURA INT NOT NULL AUTO_INCREMENT,
    ID_CLIENTE_FK INT,
    FECHA DATE,
    ID_VENDEDOR_FK INT,
    PRIMARY KEY (NRO_FACTURA),
    FOREIGN KEY (ID_CLIENTE_FK) REFERENCES CLIENTE (ID_CLIENTE),
    FOREIGN KEY (ID_VENDEDOR_FK) REFERENCES VENDEDOR (ID_EMPLEADO)
);

CREATE TABLE PRODUCTO (
    ID_PRODUCTO INT NOT NULL AUTO_INCREMENT,
    DESCRIPCION VARCHAR(50) NOT NULL,
    ESTADO ENUM('Sin Stock','En Stock'),
    ID_PROV_FK INT,
    PRIMARY KEY (ID_PRODUCTO),
    FOREIGN KEY (ID_PROV_FK) REFERENCES PROVEEDOR (ID_PROV)
);

CREATE TABLE DETALLE_VENTA (
    NRO_DETALLE INT NOT NULL,
    NRO_FACTURA_FK INT NOT NULL,
    ID_PRODUCTO_FK INT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO FLOAT,
    PRIMARY KEY (NRO_DETALLE),
    FOREIGN KEY (NRO_FACTURA_FK) REFERENCES VENTA (NRO_FACTURA),
    FOREIGN KEY (ID_PRODUCTO_FK) REFERENCES PRODUCTO (ID_PRODUCTO)
);

#INSERTS

INSERT INTO PROVEEDOR (NOMBRE, CUID, CIUDAD) 
VALUES ('ARCOR', '30111222339', 'San Luis'), 
('Molinos', '30222333448', 'Cordoba'), 
('Marolio', '30333444557', 'San Luis'), 
('Ledesma', '30444555666', 'Capital Federal'), 
('Johnson', '30555666775', 'Ramos Mejia'); 

#----

INSERT INTO PRODUCTO(DESCRIPCION, ESTADO, ID_PROV_FK) 
VALUES ('Harina', 'En Stock', 2), 
('Arroz', 'En Stock', 1), 
('Jabon liquido', 'Sin Stock', 5), 
('Azucar', 'En Stock', 4), 
('Aceite', 'Sin Stock', 3),
('Cafe','En Stock',2); 

#----

INSERT INTO CLIENTE (NOMBRE) 
VALUES ('Juan Carlos Altamirano'), 
('Pepe Silla'), 
('Esteban Quito'), 
('Laura Noveas'), 
('Alejandra Hola'); 

#----

INSERT INTO VENDEDOR (NOMBRE, APELLIDO, DNI, CIUDAD) 
VALUES ('Ambar', 'Paredes', 33444555, 'San Pedro'), 
('Federico', 'Medina', 34555666, 'Mar del Plata'), 
('Gaston', 'Salvatierra', 35666777, 'Buenos Aires'), 
('Florencia', 'Luque', 36777888, 'Bariloche'), 
('Leandro', 'Fido', 37888999, 'San Luis'); 


# -----

INSERT INTO VENTA(ID_CLIENTE_FK, FECHA, ID_VENDEDOR_FK) 
VALUES 
(1, '1998-05-01', 3), 
(4, '2015-02-24', 5), 
(2, '2020-03-31', 5), 
(3, '2020-04-12', 2), 
(4, '2021-10-02', 1), 
(5, '2021-11-06', 1), 
(3, '2022-02-16', 4), 
(5, '2022-03-07', 1), 
(1, '2022-03-15', 2), 
(5, '1998-05-15', 5); 

#-----

INSERT INTO DETALLE_VENTA (NRO_FACTURA_FK, NRO_DETALLE, ID_PRODUCTO_FK, 
CANTIDAD, PRECIO_UNITARIO) 
VALUES
(1, 1,  1, 4, 100.80), 
(2, 2,  2, 8, 80.50), 
(3, 3,  4, 10, 200.35), 
(4, 4,  3, 23, 89.99), 
(5, 5,  3, 54, 154.87), 
(6, 6,  2, 19, 321.56), 
(7, 7,  2, 11, 452.84), 
(8, 8,  4, 5, 163.12), 
(9, 9,  4, 3, 56.77), 
(10,10, 5, 15, 199.66); 

#-----
SELECT * FROM VENTA;

#---

DROP TABLE DETALLE_VENTA

# <---->
# 1

SELECT * FROM PRODUCTO P , PROVEEDOR PROV 
WHERE P.ID_PROV_FK = PROV.ID_PROV AND PROV.CIUDAD 
LIKE 'San Luis' ORDER BY ID_PRODUCTO ASC;

SELECT P.DESCRIPCION AS DESCRIPCION_DEL_PRODUCTO FROM PRODUCTO P 
JOIN PROVEEDOR PROV ON P.ID_PROV_FK = PROV.ID_PROV 
WHERE PROV.CIUDAD 
LIKE 'San Luis' ORDER BY P.DESCRIPCION;

# <---->
# 2

# TODOS LOS ELEMENTOS DE PRODUCTO DEBEN APARECER EN EL RESULTADO FINAL -> EN ALGUN DETALLE VENTA

SELECT * FROM PRODUCTO PRODUCT LEFT JOIN DETALLE_VENTA DV 
ON PRODUCT.ID_PRODUCTO = 
DV.ID_PRODUCTO_FK WHERE PRODUCT.ESTADO LIKE 'En Stock'
AND DV.NRO_FACTURA IS NULL ;

# <---->
# 3
SELECT DESCRIPCION FROM PRODUCTO PRODUCT JOIN DETALLE_VENTA DV 
ON PRODUCT.ID_PRODUCTO = DV.ID_PRODUCTO_FK 							   #LISTA DE MESES
JOIN  VENTA V ON V.NRO_FACTURA = DV.NRO_FACTURA_FK WHERE MONTH(V.FECHA) NOT IN (3,5,10,12) OR YEAR (V.FECHA) NOT IN (2020,2021);

# <---->
# 4 AGREGACIÓN

SELECT P.DESCRIPCION , VEND.APELLIDO , sum(DV.CANTIDAD) CANTIDAD FROM PRODUCTO P
JOIN DETALLE_VENTA DV
ON P.ID_PRODUCTO = DV.ID_PRODUCTO_FK
JOIN VENTA V ON V.NRO_FACTURA = DV.NRO_FACTURA_FK
JOIN VENDEDOR VEND ON VEND.ID_EMPLEADO = V.ID_VENDEDOR_FK;

# <---->
# 5 AGREGACIÓN
 
# <---->
# 6
SELECT VT.NRO_FACTURA,VD.NOMBRE,VT.FECHA FROM VENTA VT JOIN VENDEDOR VD ON VT.ID_VENDEDOR_FK = 
VD.ID_EMPLEADO WHERE VT.FECHA LIKE '%2015%' ORDER BY VD.NOMBRE , VD.APELLIDO ;
